name: TanksMobEggSpawnerBlocker
version: '1.0'
main: me.sothatsit.mobeggspawnerblocker.MobEggSpawnerBlocker
api-version: '1.21'
commands:
  mobeggspawnerblocker:
    description: Reload the configuration
    permission: mobeggspawnerblocker.reload
permissions:
  mobeggspawnerblocker.reload:
    description: Allows you to reload the config
    default: op
  mobeggspawnerblocker.override:
    description: Allows you to use eggs on spawners
    default: op

